---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Run controller stop pytest verifier
      vars:
        scenario_root: "{{ playbook_dir }}"
      ansible.builtin.command:
        cmd: >
          uv run pytest -q {{ scenario_root }}/tests
        chdir: "{{ lookup('env','MOLECULE_SCENARIO_DIRECTORY') | default(scenario_root) }}"
      environment:
        PYTHON: "{{ lookup('env', 'PYTHON') | default('python3') }}"
      register: controller_test
      changed_when: false
    - name: Show controller output
      ansible.builtin.debug:
        var: controller_test.stdout
